### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by abdrehman98** [SeijiV13/Angular-AWS-Lambda#1]
Hi I was following your guide: [https://www.seijivillafranca.com/post/serverless-angular-with-aws-lambda](https://www.seijivillafranca.com/post/serverless-angular-with-aws-lambda)

I am facing two issues, can you please help:

1. When I run `npm run serve:serverless` it gives me this error:

```console
> angular-ssr-serverless-deployment@0.0.0 serve:serverless
> serverless offline start

Environment: linux, node 16.14.2, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Unexpected "handler" function configuration: Expected object received 'lambda.handler')
```

2. In your article you haven't explained the implementation of `npm run serverless:deploy`

Thanks in advance for the help

**Comment by HugoxSaraiva** [comment]
Hello, I had the same issue when following his guide.
To answer your first question, the error occurs due to an indentation error. To solve it, you should change the last lines of your **serverless.yaml** to the following lines (notice the indentation):
```
functions:
  api:
    handler: lambda.handler
    events:
      - http: GET {proxy+}
      - http: GET /
```

**Comment by HugoxSaraiva** [comment]
For your second question, you can use the deploy script available on **package.json** "to deploy the stack on your aws account (don't forget to configure serverless with your aws credentials beforehand).

**Comment by abdrehman98** [comment]
Thanks @HugoxSaraiva
